@IsTest
private class SetupArchiveErrors_Test {


    @IsTest
    private static void happyPath() {

        // Setup


        // Exercise



        // Verify
        System.assert(false, 'TODO: Implement tests');
    }


    @IsTest
    private static void overwritesExistingJob() {

        // Setup


        // Exercise



        // Verify
        System.assert(false, 'TODO: Implement tests');
    }
}